server:
  port: 8080
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/instagramDb
      database: instagramDb
      username: root
      password: root
      host: localhost
    
              
## features
swagger:
  title: Instagram
  description:
  icense:
  basePackage: com.knayam.instagramapi
  
management:
  endpoints:
    web:
      exposure:
        include: health
        
  